# Продвинутая работа с NumPy

## 1. Генерация случайных чисел

NumPy предоставляет мощную подсистему для генерации псевдослучайных чисел через модуль `numpy.random`. Современный подход использует `Generator` объекты.

### Инициализация генератора

In [121]:
import numpy as np
from numpy.random import default_rng

# Создание генератора с seed для воспроизводимости
rng = default_rng(42)

# Генератор без seed (каждый раз разные результаты)
rng = default_rng()

### Целые случайные числа

In [122]:
# Случайные целые числа в диапазоне [0, 10)
rng.integers(0, 10, size=5)

array([7, 4, 7, 4, 5])

In [123]:
# Случайные целые числа в форме матрицы
rng.integers(1, 100, size=(3, 4))

array([[89, 85, 87, 70],
       [98, 91, 83, 30],
       [31, 50,  4, 44]])

In [124]:
# Включая верхнюю границу
rng.integers(1, 6, size=10, endpoint=True)  # Кубик 1-6

array([4, 5, 4, 5, 6, 6, 2, 1, 6, 2])

### Дробные случайные числа

In [125]:
# Случайные дробные числа от 0 до 1
rng.random(5)

array([0.26587329, 0.23740847, 0.77552564, 0.65064398, 0.34007572])

In [126]:
# Случайные дробные числа от 0 до 1 в форме матрицы
rng.random((2, 3))

array([[0.20928755, 0.37761648, 0.73793297],
       [0.38747505, 0.88130636, 0.78161035]])

In [127]:
# Случайные дробные числа от 1 до 5 включая 1, исключая 5
rng.random(5) * 4 + 1  # Масштабирование и сдвиг

array([1.40027964, 2.77829496, 2.06875899, 3.20922167, 3.22082456])

In [128]:
# Случайные дробные числа от -5 до 0 невключая 0
rng.random((3, 2)) * 5 - 5

array([[-2.08112466, -2.80673317],
       [-1.06037015, -1.16286682],
       [-1.89332613, -3.43628479]])

In [129]:
# Случайные дробные числа от 1 до 5 включая 1, исключая 5
rng.uniform(1, 5, size=5)

array([1.85708792, 4.16582884, 1.74337624, 3.36022803, 2.63944364])

In [130]:
# Случайные числа в заданном диапазоне [10.0, 20.0) в форме матрицы
rng.uniform(10.0, 20.0, size=(2, 3))

array([[14.45660359, 16.94350687, 13.61377441],
       [18.61589676, 10.17139837, 18.70254619]])

### Выборки из нормального распределения

In [131]:
# Выборка из 10 элементов из стандартного нормального распределения (μ=0, σ=1)
rng.standard_normal(10)

array([-0.83904797, -0.96781498,  0.46563058,  1.27614902, -0.80745661,
       -0.08335098,  0.05871729,  0.6493748 ,  2.11247686, -1.53755742])

In [132]:
# Нормальное распределение с заданными параметрами
# μ=100, σ=15 (например, IQ тесты)
rng.normal(100, 15, size=8)

array([ 97.70037594, 120.07494777, 109.21270734,  85.79852162,
       107.81570492, 108.87959189, 116.12075252, 123.98753021])

In [133]:
# Многомерное нормальное распределение
mean = [0, 0]
cov = [[1, 0.5], [0.5, 2]]
rng.multivariate_normal(mean, cov, size=5)

array([[ 2.14557356, -0.17696184],
       [-2.15653129, -1.04533876],
       [ 0.9782958 , -0.01778011],
       [-0.70693695, -1.23452177],
       [-0.77250879,  0.07349149]])

### Выборки из равномерного распределения

In [134]:
# Равномерное распределение на [0, 1)
rng.uniform(size=5)

array([0.15369632, 0.81470596, 0.82597946, 0.48502534, 0.38353812])

In [135]:
# Равномерное распределение на [a, b)
rng.uniform(-5, 5, size=8)

array([-0.67767026,  4.77924922, -2.56671741, -2.67142352, -2.83799981,
       -1.47571878, -0.42968255,  2.04009751])

In [136]:
# Равномерное распределение для матрицы
rng.uniform(0, 100, size=(2, 3))

array([[18.21206711, 67.2253633 , 23.82359877],
       [89.17490462, 40.15754605, 11.46163045]])

### Выбор элементов из массива

In [137]:
# Исходный массив
arr = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])

In [138]:
# Выбор одного случайного элемента
rng.choice(arr)

np.str_('cherry')

In [139]:
# Выбор нескольких элементов с возвращением
rng.choice(arr, size=3)

array(['cherry', 'elderberry', 'date'], dtype='<U10')

In [140]:
# Выбор без возвращения
rng.choice(arr, size=3, replace=False)

array(['cherry', 'banana', 'date'], dtype='<U10')

In [141]:
# Выбор с заданными вероятностями
probabilities = [0.1, 0.2, 0.3, 0.3, 0.1]
rng.choice(arr, size=10, p=probabilities)

array(['date', 'cherry', 'banana', 'date', 'banana', 'cherry', 'date',
       'date', 'banana', 'banana'], dtype='<U10')

### Перемешивание массивов

In [142]:
# Перемешивание существующего массива (изменяет исходный)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
rng.shuffle(arr) # Изменяет arr на месте
print(arr)

[ 9  6  4  2  5  1 10  7  3  8]


In [143]:
# Создание перемешанной копии (не изменяет исходный)
original = np.array([1, 2, 3, 4, 5])
shuffled = rng.permutation(original)
print(original)
print(shuffled)

[1 2 3 4 5]
[4 5 3 2 1]


In [144]:
# Случайная перестановка индексов
indices = rng.permutation(len(arr))
shuffled_arr = arr[indices]

## 2. Статистические функции

NumPy предоставляет обширный набор статистических функций для анализа данных.

### Меры центральной тенденции

In [145]:
# Для одномерных массивов
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Data:", data)

# Среднее арифметическое
mean = np.mean(data)
print("Mean:", mean)

# Медиана
median = np.median(data)
print("Median:", median)

Data: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Median: 5.5


In [146]:
# Для многомерных массивов
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)

# Среднее по всем элементам
mean_all= np.mean(matrix)  # 5.0
print("Mean of all elements:", mean_all)

# Среднее по оси (axis=0 - по столбцам, axis=1 - по строкам)
mean_col = np.mean(matrix, axis=0)
print("Mean of each column:", mean_col)

mean_row = np.mean(matrix, axis=1)
print("Mean of each row:", mean_row)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean of all elements: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]


### Дисперсия и стандартное отклонение

In [147]:
# Для одномерных массивов
data = np.array([2, 4, 4, 4, 5, 5, 7, 9])
print("Data:", data)

# Смещенная дисперсия (делитель n)
var_biased = np.var(data)  # ddof=0 по умолчанию
print("Biased Variance:", var_biased)

# Несмещенная дисперсия (делитель n-1)
var_unbiased = np.var(data, ddof=1)
print("Unbiased Variance:", var_unbiased)

# Смещенное стандартное отклонение (делитель n)
std_dev_biased = np.std(data)  # ddof=0 по умолчанию
print("Biased Standard Deviation:", std_dev_biased)

# Несмещенное стандартное отклонение (делитель n-1)
std_dev_unbiased = np.std(data, ddof=1)
print("Unbiased Standard Deviation:", std_dev_unbiased)

Data: [2 4 4 4 5 5 7 9]
Biased Variance: 4.0
Unbiased Variance: 4.571428571428571
Biased Standard Deviation: 2.0
Unbiased Standard Deviation: 2.138089935299395


In [148]:
# Для многомерных массивов
matrix = rng.normal(10, 2, size=(5, 4))
print("Matrix:\n", matrix)

# Смещенная дисперсия по оси (axis=0 - по столбцам, axis=1 - по строкам)
var_biased = np.var(matrix, ddof=0, axis=0)   # Дисперсия по столбцам
print("Biased Variance of each column:", var_biased)

# Смещенное стандартное отклонение по оси (axis=0 - по столбцам, axis=1 - по строкам)
std_dev_biased = np.std(matrix, ddof=1, axis=1)   # Стд. откл. по строкам
print("Biased Standard Deviation of each row:", std_dev_biased)

Matrix:
 [[ 9.53443975  8.55655595  9.60935605  9.2546551 ]
 [10.66646229  9.89282444 12.32386731  9.44800146]
 [10.54555055 10.33855863 10.23000614  6.11989338]
 [ 7.61378277  9.1176857  10.41495481  9.95394356]
 [12.83710107 10.48488084  9.43653     8.25032808]]
Biased Variance of each column: [2.8829992  0.54102655 1.05674719 1.85077967]
Biased Standard Deviation of each row: [0.47973012 1.26519416 2.12976529 1.23083329 1.95009937]


### Квантили и перцентили

In [149]:
# Для одномерных массивов
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Data:", data)
# Перцентили
np.percentile(data, 25)   # 1-й квартиль: 3.25
np.percentile(data, 50)   # Медиана: 5.5
np.percentile(data, 75)   # 3-й квартиль: 7.75
np.percentile(data, 90)   # 90-й перцентиль: 9.1

Data: [ 1  2  3  4  5  6  7  8  9 10]


np.float64(9.1)

In [150]:
# Несколько перцентилей одновременно
np.percentile(data, [25, 50, 75])

array([3.25, 5.5 , 7.75])

In [151]:
# Квантили (более общая функция)
np.quantile(data, 0.25)   # То же что 25-й перцентиль

np.float64(3.25)

In [152]:
# несколько квантилей
np.quantile(data, [0.1, 0.5, 0.9])

array([1.9, 5.5, 9.1])

In [153]:
# Для многомерных массивов
matrix = rng.integers(1, 100, size=(6, 4))
np.percentile(matrix, 50, axis=0)  # Медиана по столбцам

array([35. , 53. , 75. , 24.5])

### Минимальные и максимальные значения

In [154]:
# Для одномерных массивов
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Data:", data)

# Минимум (Наименьшее значение)
minimum = np.min(data)
print("Minimum:", minimum)

# Максимум (Наибольшее значение)
maximum = np.max(data)
print("Maximum:", maximum)

# Размах (разность между max и min)
sample_range= np.ptp(data)
print("Range of data:", sample_range)

Data: [ 1  2  3  4  5  6  7  8  9 10]
Minimum: 1
Maximum: 10
Range of data: 9


In [155]:
# Для многомерных массивов
matrix = np.array([[1, 8, 3], [4, 2, 6], [7, 5, 9]])

np.min(matrix)           # 1 - общий минимум
np.min(matrix, axis=0)   # array([1, 2, 3]) - минимум по столбцам
np.min(matrix, axis=1)   # array([1, 2, 5]) - минимум по строкам

np.max(matrix, axis=0)   # array([7, 8, 9]) - максимум по столбцам

array([7, 8, 9])

### Дополнительные статистики

In [156]:
# Размах межквартильный
q75, q25 = np.percentile(data, [75, 25])
iqr = q75 - q25
print(f"Межквартильный размах: {iqr}")

Межквартильный размах: 4.5


In [157]:
# Ковариация между массивами
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 1, 3, 5])
covariance_matrix = np.cov(x, y)
covariance = covariance_matrix[0, 1]
print(f"Ковариация: {covariance}")

Ковариация: 1.25


In [158]:
# Корреляция между массивами
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 1, 3, 5])
correlation_matrix = np.corrcoef(x, y)
correlation = correlation_matrix[0, 1]
print(f"Корреляция: {correlation}")

Корреляция: 0.49999999999999994


## 3. Обработка пропусков и NaN

NumPy предоставляет специальные функции для работы с пропущенными значениями (NaN - Not a Number).

### Создание и обнаружение NaN

In [159]:
# Создание массива с NaN
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan, 7.0])

# Проверка на NaN
np.isnan(data)

array([False, False,  True, False, False,  True, False])

In [160]:
# Количество NaN значений
np.sum(np.isnan(data))

np.int64(2)

In [161]:
# Проверка наличия хотя бы одного NaN
np.any(np.isnan(data))

np.True_

In [162]:
# Проверка, что все значения не NaN
np.all(~np.isnan(data))

np.False_

### Статистические функции с NaN
NumPy предоставляет версии статистических функций, которые игнорируют NaN значения:

In [163]:
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan, 7.0])

# Обычные функции возвращают NaN при наличии NaN в данных
np.mean(data)    # nan
np.sum(data)     # nan

# Функции с префиксом "nan" игнорируют NaN
np.nanmean(data)    # 3.8
np.nansum(data)     # 19.0
np.nanstd(data)     # 2.23606797749979
np.nanvar(data)     # 5.0
np.nanmin(data)     # 1.0
np.nanmax(data)     # 7.0
np.nanmedian(data)  # 4.0

# Квантили с NaN
np.nanpercentile(data, [25, 50, 75])
# array([2. , 4. , 5.5])

array([2., 4., 5.])

### Обработка NaN в многомерных массивах

In [191]:
# Создание матрицы с NaN
matrix = np.array([[1.0, 2.0, np.nan],
                   [4.0, np.nan, 6.0],
                   [7.0, 8.0, 9.0]])
print(matrix)

# Статистики по осям
np.nanmean(matrix, axis=0)  # array([4. , 5. , 7.5])
np.nanmean(matrix, axis=1)  # array([1.5, 5. , 8. ])

# Подсчет не-NaN элементов по осям
np.sum(~np.isnan(matrix), axis=0)  # array([3, 2, 2])
np.sum(~np.isnan(matrix), axis=1)  # array([2, 2, 3])

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


array([2, 2, 3])

### Удаление и замена NaN

In [190]:
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.nan, 7.0])
print(data)
# Фильтрация NaN (удаление)
clean_data = data[~np.isnan(data)]
clean_data

[ 1.  2. nan  4.  5. nan  7.]


array([1., 2., 4., 5., 7.])

In [166]:
# Замена NaN на конкретное значение
filled_data = np.nan_to_num(data, nan=0.0)
filled_data

array([1., 2., 0., 4., 5., 0., 7.])

In [167]:
# Замена NaN на среднее значение
mean_value = np.nanmean(data)
data_filled = np.where(np.isnan(data), mean_value, data)
data_filled

array([1. , 2. , 3.8, 4. , 5. , 3.8, 7. ])

### Обработка бесконечности

In [ ]:
# Создание массива с бесконечными значениями
data = np.array([1.0, np.inf, -np.inf, 4.0, 5.0])
print(data)
# Проверка на бесконечность
np.isinf(data)

array([False,  True,  True, False, False])

In [172]:
# Проверка на положительную бесконечность
np.isposinf(data)        # array([False,  True, False, False, False])

array([False,  True, False, False, False])

In [173]:
# Проверка на отрицательную бесконечность
np.isneginf(data)        # array([False,  True, False, False, False])

array([False, False,  True, False, False])

In [169]:
# Проверка на конечность
np.isfinite(data)        # array([ True, False, False,  True,  True])

array([ True, False, False,  True,  True])

In [170]:
# Замена бесконечных значений
np.nan_to_num(data, posinf=999, neginf=-999)

array([   1.,  999., -999.,    4.,    5.])

## 4. Функции поиска
NumPy предоставляет мощные функции для поиска элементов и индексов в массивах

### Функция where()

In [ ]:
# Базовое использование where для условной фильтрации
data = np.array([1, 5, 3, 8, 2, 9, 4])
print(data)

# Поиск индексов элементов, удовлетворяющих условию
indices = np.where(data > 5)
print(indices)
print(data[indices])

[1 5 3 8 2 9 4]
(array([3, 5]),)
[8 9]


In [175]:
# Условная замена значений
result = np.where(data > 5, data, 0)  # Если > 5, оставить, иначе 0
result

array([0, 0, 0, 8, 0, 9, 0])

In [182]:
# Сложные условия
conditions = ((data > 3) & 
              (data < 7)
              )
result = np.where(conditions, data, -1)
result

array([-1,  5, -1, -1, -1, -1,  4])

In [193]:
# Многомерные массивы
matrix = np.array([[1, 8, 3], [4, 2, 9], [7, 5, 6]])
print(matrix)

row_indices, col_indices = np.where(matrix > 5)
print(f"Строки: {row_indices}, Столбцы: {col_indices}")

[[1 8 3]
 [4 2 9]
 [7 5 6]]
Строки: [0 1 2 2], Столбцы: [1 2 0 2]


In [183]:
# Значения, удовлетворяющие условию
values = matrix[row_indices, col_indices]
print(values)

[8 9 7 6]


### argmin() и argmax()

In [194]:
data = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(data)

# Индекс минимального элемента
min_index = np.argmin(data)
print(f"Минимальный элемент: {data[min_index]} в позиции {min_index}")

# Индекс максимального элемента
max_index = np.argmax(data)
print(f"Максимальный элемент: {data[max_index]} в позиции {max_index}")

[3 1 4 1 5 9 2 6]
Минимальный элемент: 1 в позиции 1
Максимальный элемент: 9 в позиции 5


In [197]:
# Для многомерных массивов
matrix = np.array([[1, 8, 3], [4, 2, 9], [7, 5, 6]])
print(matrix)

# индексы минимумов по столбцам
np.argmin(matrix, axis=0)

[[1 8 3]
 [4 2 9]
 [7 5 6]]


array([0, 1, 0])

In [ ]:
# индексы минимумов по строкам
np.argmin(matrix, axis=1) 

array([0, 1, 1])

### Функции поиска с NaN

In [ ]:
data = np.array([3.0, np.nan, 4.0, 1.0, 5.0, np.nan, 2.0])

# Обычные функции могут работать некорректно с NaN
np.argmin(data)  # 1 (находит NaN как минимум)
np.argmax(data)  # 1 (находит NaN как максимум)

# Функции, игнорирующие NaN
np.nanargmin(data)  # 3 (индекс значения 1.0)
np.nanargmax(data)  # 4 (индекс значения 5.0)

# Для многомерных массивов
matrix = np.array([[1.0, np.nan, 3.0], 
                   [4.0, 2.0, np.nan], 
                   [np.nan, 5.0, 6.0]])

# Поиск с игнорированием NaN
np.nanargmin(matrix, axis=0)  # array([0, 1, 0])
np.nanargmax(matrix, axis=1)  # array([2, 0, 2])

## 5. Продвинутая индексация

NumPy поддерживает два типа продвинутой индексации: булевую и fancy индексацию.

### Булевая индексация

In [199]:
# Создание данных
data = np.array([1, 5, 3, 8, 2, 9, 4, 6])
print(data)

# Создание булевой маски
mask = data > 5
print(mask)

[1 5 3 8 2 9 4 6]
[False False False  True False  True False  True]


In [200]:
# Создание данных
data = np.array([1, 5, 3, 8, 2, 9, 4, 6])
print(data)

# Использование маски для фильтрации
filtered_data = data[mask]
print(filtered_data)

[1 5 3 8 2 9 4 6]
[8 9 6]


In [202]:
# Создание данных
data = np.array([1, 5, 3, 8, 2, 9, 4, 6])
print(data)

# Комбинированные условия
complex_mask = (data > 3) & (data < 7)
print(data[complex_mask])

[1 5 3 8 2 9 4 6]
[5 4 6]


In [203]:
# Создание данных
data = np.array([1, 5, 3, 8, 2, 9, 4, 6])
print(data)

# Логические операторы для масок
mask1 = data > 5
mask2 = data % 2 == 0  # четные числа
print(data[mask1 | mask2])  # ИЛИ
print(data[mask1 & mask2])  # И
print(data[~mask1])         # НЕ

[1 5 3 8 2 9 4 6]
[8 2 9 4 6]
[8 6]
[1 5 3 2 4]


In [ ]:
# Булевая индексация для многомерных массивов
matrix = np.array([[1, 8, 3], [4, 2, 9], [7, 5, 6]])
print(matrix)

# Фильтрация элементов, удовлетворяющих условию
print(matrix[matrix > 5])

# Построчная фильтрация
row_sums = np.sum(matrix, axis=1)
row_mask = row_sums > 15
print(matrix[row_mask])  # Строки с суммой > 15

# Изменение значений через булевую индексацию
data_copy = data.copy()
data_copy[data_copy > 5] = 99
print(data_copy)

[[1 8 3]
 [4 2 9]
 [7 5 6]]
[8 9 7 6]
[[7 5 6]]
[99 99 99 99 99 99 99 99]


### Fancy индексация (индексация массивами)

In [204]:
# Индексация массивом индексов
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(data)

# Выбор элементов по списку индексов
indices = [1, 3, 5, 7]
selected = data[indices]
print(selected)

[10 20 30 40 50 60 70 80]
[20 40 60 80]


In [206]:
# Индексация массивом индексов
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(data)

# Индексы могут повторяться
indices = [0, 0, 2, 2, 4]
print(data[indices])

[10 20 30 40 50 60 70 80]
[10 10 30 30 50]


In [ ]:
# Fancy индексация для многомерных массивов
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Выбор строк
row_indices = [0, 2, 3]
print(matrix[row_indices])

### Расширенная индексация с условиями

In [208]:
# Создание данных
scores = np.array([[85, 92, 78], [76, 88, 95], [91, 83, 87], [69, 79, 84]])
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])

# Поиск студентов со средним баллом > 85
avg_scores = np.mean(scores, axis=1)
high_achievers_mask = avg_scores > 85
high_achievers = names[high_achievers_mask]
high_scores = scores[high_achievers_mask]

print("Студенты с высокими оценками:")
for name, score_row in zip(high_achievers, high_scores):
    print(f"{name}: {score_row}, среднее: {np.mean(score_row):.1f}")

# Индексация по нескольким условиям
math_scores = scores[:, 0]
english_scores = scores[:, 1] 
science_scores = scores[:, 2]

# Студенты с математикой > 80 И английским > 85
mask = (math_scores > 80) & (english_scores > 85)
selected_students = names[mask]
print(f"Студенты с математикой > 80 И английским > 85: {selected_students}")

# Сортировка по индексам
sort_indices = np.argsort(avg_scores)[::-1]  # По убыванию
sorted_names = names[sort_indices]
sorted_scores = scores[sort_indices]
print(f"Рейтинг: {sorted_names}")

Студенты с высокими оценками:
Bob: [76 88 95], среднее: 86.3
Charlie: [91 83 87], среднее: 87.0
Студенты с математикой > 80 И английским > 85: ['Alice']
Рейтинг: ['Charlie' 'Bob' 'Alice' 'David']


### Изменение значений через продвинутую индексацию

In [210]:
# Исходные данные
data = np.array([10, 20, 30, 40, 50])
print(data)

# Изменение через булевую индексацию
data[data > 30] *= 2  # Удваиваем значения > 30
print(data)

# Изменение через fancy индексацию
data[[0, 2, 4]] = 999
print(data)

# Многомерные массивы
matrix = np.arange(12).reshape(3, 4)
print("Исходная матрица:")
print(matrix)

# Изменение целых строк
matrix[[0, 2]] = 0
print("После изменения строк 0 и 2:")
print(matrix)

# Условное изменение
matrix[matrix < 5] = -1
print("После условного изменения:")
print(matrix)

[10 20 30 40 50]
[ 10  20  30  80 100]
[999  20 999  80 999]
Исходная матрица:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
После изменения строк 0 и 2:
[[0 0 0 0]
 [4 5 6 7]
 [0 0 0 0]]
После условного изменения:
[[-1 -1 -1 -1]
 [-1  5  6  7]
 [-1 -1 -1 -1]]


## 6. Линейная алгебра
NumPy предоставляет обширные возможности для работы с линейной алгеброй через модуль `numpy.linalg`.

### Основные операции с векторами

In [211]:
# Создание векторов
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Скалярное произведение
dot_product = np.dot(u, v)
# или
dot_product = u @ v  # Оператор матричного умножения
print(f"Скалярное произведение: {dot_product}")

Скалярное произведение: 32


In [212]:
# Норма вектора (длина)
norm_u = np.linalg.norm(u)
print(f"Норма вектора u: {norm_u:.3f}")  # 3.742

# Различные типы норм
l1_norm = np.linalg.norm(u, ord=1)        # L1 норма (сумма абс. значений)
l2_norm = np.linalg.norm(u, ord=2)        # L2 норма (евклидова)
inf_norm = np.linalg.norm(u, ord=np.inf)  # Максимальная норма

Норма вектора u: 3.742


In [213]:
# Нормализация вектора
u_normalized = u / np.linalg.norm(u)
print(f"Нормализованный вектор: {u_normalized}")

Нормализованный вектор: [0.26726124 0.53452248 0.80178373]


In [214]:
# Векторное произведение (для 3D векторов)
cross_product = np.cross(u, v)
print(f"Векторное произведение: {cross_product}")

Векторное произведение: [-3  6 -3]


### Матричные операции

In [215]:
# Создание матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Матричное умножение
C = np.dot(A, B)  # или A @ B
print("A @ B =")
print(C)

A @ B =
[[19 22]
 [43 50]]


In [216]:
# Транспонирование
A_T = A.T  # или np.transpose(A)
print("Транспонированная матрица A:")
print(A_T)

Транспонированная матрица A:
[[1 3]
 [2 4]]


In [217]:
# Определитель
det_A = np.linalg.det(A)
print(f"Определитель A: {det_A}")

Определитель A: -2.0000000000000004


In [218]:
# Обратная матрица
A_inv = np.linalg.inv(A)
print("Обратная матрица A:")
print(A_inv)

# Проверка: A * A^(-1) = I
identity_check = A @ A_inv
print("A @ A^(-1) =")
print(identity_check)

Обратная матрица A:
[[-2.   1. ]
 [ 1.5 -0.5]]
A @ A^(-1) =
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [220]:
# След матрицы (сумма диагональных элементов)
trace_A = np.trace(A)
print(f"След матрицы A: {trace_A}")

След матрицы A: 5


### Системы линейных уравнений

In [221]:
# Система уравнений Ax = b
# 2x + y = 3
# x + 3y = 4
A = np.array([[2, 1], [1, 3]])
print("A:", A)
b = np.array([3, 4])
print("b:", b)

A: [[2 1]
 [1 3]]
b: [3 4]


In [222]:
# Решение системы
x = np.linalg.solve(A, b)
print(f"Решение системы: x = {x}")

Решение системы: x = [1. 1.]


In [223]:
# Проверка решения
check = A @ x
print(f"Проверка: A @ x = {check}")

Проверка: A @ x = [3. 4.]
